alert("Самая первая реализация JavaScript была создана Бренданом Эйхом в компании Netscape, и с тех пор обновляется, чтобы соответствовать ECMA-262 Edition 5 и более поздним версиям.")
alert("Синтаксис JavaScript был создан всего за 10 дней на базе синтаксиса Java.")
alert("JavaScript был впервые представлен в 1995 году. ")
alert("JavaScript — это не Java")
alert("ECMAScript")
